/* MySql */
CREATE DATABASE cardapiumDB DEFAULT CHARACTER SET utf8;

USE cardapiumDB;


CREATE TABLE IF NOT EXISTS cardapiumDB.TB_CATEGORIA (
	id int NOT NULL AUTO_INCREMENT,
	nome varchar(255) NOT NULL,
	PRIMARY KEY (id)
)ENGINE = InnoDB;



CREATE TABLE IF NOT EXISTS cardapiumDB.TB_ITENS (
	id int NOT NULL AUTO_INCREMENT,
	idCategoria int NOT NULL,
	nome varchar(255) NOT NULL,
	descricao TEXT NULL,
	foto varchar(500) NULL,
	preco DECIMAL(10, 2) NOT NULL,
	PRIMARY KEY (id),
	CONSTRAINT FK_ITENS_CATEGORIA FOREIGN KEY (idCategoria) 
	REFERENCES TB_CATEGORIA(id)
		ON DELETE NO ACTION
		ON UPDATE CASCADE
)ENGINE = InnoDB;



CREATE TABLE IF NOT EXISTS cardapiumDB.TB_USUARIO (
    id INT NOT NULL AUTO_INCREMENT,
    nome VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    data_nascimento DATE NULL,
    telefone VARCHAR(20) NULL,
    senha VARCHAR(255) NOT NULL,
    cep VARCHAR(10) NULL,
    rua VARCHAR(255) NULL,
    numero VARCHAR(10) NULL,
    bairro VARCHAR(100) NULL,
    complemento VARCHAR(100) NULL,
    cidade VARCHAR(100) NULL,
    estado CHAR(2) NULL,
    PRIMARY KEY (id)
)ENGINE = InnoDB;


CREATE TABLE IF NOT EXISTS cardapiumDB.TB_PEDIDOS (
	id int NOT NULL AUTO_INCREMENT,
	preco DECIMAL(10,2) NOT NULL,
	nome varchar(255) NOT NULL,
	idUsuario int NOT NULL,
	finalizado tinyint NOT NULL,
	PRIMARY KEY (id),
	CONSTRAINT FK_PEDIDO_USUARIO FOREIGN KEY (idUsuario)
		REFERENCES TB_USUARIO(id)
		ON DELETE CASCADE
		ON UPDATE CASCADE
)ENGINE = InnoDB;


CREATE TABLE IF NOT EXISTS cardapiumDB.TB_ITENS_PEDIDOS(
    id INT NOT NULL AUTO_INCREMENT,
    idPedido INT NOT NULL,
    idItem INT NOT NULL,
    quantidade INT NOT NULL,
    preco DECIMAL(10,2) NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT FK_ITENS FOREIGN KEY (idItem)
        REFERENCES TB_ITENS(id)
            ON DELETE CASCADE
            ON UPDATE CASCADE,
    CONSTRAINT FK_PEDIDOS FOREIGN KEY (idPedido)
        REFERENCES TB_PEDIDOS (id)
            ON DELETE CASCADE
            ON UPDATE CASCADE
)ENGINE = InnoDB;